name: Greeting from Mona

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy To Server
    runs-on: windows-latest
    steps:
      - name: Add VPN Connection
        run: |
          Add-VpnConnection -Name "VPN" -ServerAddress "${{ secrets.VPN_SERVER }}" -TunnelType "L2tp" -L2tpPsk "${{ secrets.VPN_PSK }}" -PassThru
      - name: Connect To VPN
        run: |
          rasdial.exe "Poisson" "${{ secrets.VPN_USERNAME }}" "${{ secrets.VPN_PASSWORD }}"
      - name: Ping Server
        run: |
          ping ${{ secrets.SERVER_URL }}